// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Farewell(arg1) {
  return window['go']['main']['App']['Farewell'](arg1);
}

export function GetCat(arg1) {
  return window['go']['main']['App']['GetCat'](arg1);
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
