// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Farewell(arg1:string):Promise<string>;

export function GetCat(arg1:string):Promise<string>;

export function GetTags():Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;
